"use client"

import { motion } from "framer-motion"
import { TweetEmbed } from "@/components/tweet-embed"
import { Button } from "@/components/ui/button"
import { Twitter, ExternalLink, Info } from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"

export type Tweet = {
  username: string
  handle: string
  text: string
  link: string
  timestamp: string
  engagement?: {
    likes: number
    retweets: number
    replies: number
  }
}

interface TweetsSectionProps {
  tweets: Tweet[]
  title?: string
  query?: string
  searchUrl?: string
}

export function TweetsSection({ tweets, title = "Social Media Buzz", query, searchUrl }: TweetsSectionProps) {
  if (!tweets || tweets.length === 0) {
    return null
  }

  const handleViewRealTweets = () => {
    if (searchUrl) {
      window.open(searchUrl, "_blank", "noopener,noreferrer")
    } else if (query) {
      const twitterSearchUrl = `https://twitter.com/search?q=${encodeURIComponent(query)}&src=typed_query&f=live`
      window.open(twitterSearchUrl, "_blank", "noopener,noreferrer")
    }
  }

  return (
    <motion.section
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.8, delay: 0.6 }}
      className="mt-12"
    >
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center">
          <Twitter className="h-6 w-6 text-blue-500 mr-2" />
          <h3 className="text-2xl font-bold">{title}</h3>
        </div>

        {(searchUrl || query) && (
          <Button onClick={handleViewRealTweets} className="bg-blue-500 hover:bg-blue-600 text-white">
            <ExternalLink className="h-4 w-4 mr-2" />
            View Real Tweets
          </Button>
        )}
      </div>

      {/* Info Card */}
      <Card className="mb-6 bg-blue-50 border-blue-200">
        <CardContent className="p-4">
          <div className="flex items-start space-x-3">
            <Info className="h-5 w-5 text-blue-600 mt-0.5" />
            <div>
              <h4 className="font-semibold text-blue-900 mb-1">AI-Generated Social Media Content</h4>
              <p className="text-sm text-blue-700">
                These tweets are generated by AI to show potential social media discussions about this topic. Click
                "View Real Tweets" to see actual Twitter conversations.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="space-y-4">
        {tweets.map((tweet, index) => (
          <TweetEmbed key={index} tweet={tweet} index={index} searchUrl={searchUrl} query={query} />
        ))}
      </div>

      <div className="mt-6 text-center">
        <p className="text-sm text-gray-500 mb-4">
          Want to see real-time discussions? Check out what people are actually saying on Twitter.
        </p>
        {(searchUrl || query) && (
          <Button
            variant="outline"
            onClick={handleViewRealTweets}
            className="border-blue-200 text-blue-600 hover:bg-blue-50 bg-transparent"
          >
            <Twitter className="h-4 w-4 mr-2" />
            Search "{query}" on Twitter
          </Button>
        )}
      </div>
    </motion.section>
  )
}
